server:
  tomcat:
    threads:
      max: 100
    accept-count: 50
  port: ${ORDER_PORT}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connection-timeout: 10000
      idleTimeout: 10000
      maximumPoolSize: 10
      minimumIdle: 5
      validation-timeout: 10000
    url: ${DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

feign:
  client:
    config: 
      catalog-api:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
  httpclient:
    enabled: true
    maxConnections: 200
    maxConnectionsPerRoute: 100
    connectionTimerRepeat: 30000
  hystrix:
    enabled: true
  url:
    product: http://product:17071

#PRODUCT:
#  ribbon:
#    eureka:
#      enabled: true
##    listOfServers: localhost:17071,localhost:17072

#eureka:
#  instance:
#    preferIpAddress: true
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_DEFAULTZONE}

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 3000
      circuitBreaker.errorThresholdPercentage: 50
      circuitBreaker.requestVolumeThreshold: 20
      metrics.rollingStats.timeInMilliseconds: 10000
      circuitBreaker.sleepWindowInMilliseconds: 5000

management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,refresh,bus-refresh
